export const SET_DASHBOARD_DATES = 'SET_DASHBOARD_DATES';
export const DAILY_ORDERS_PROFILE='DAILY_ORDERS_PROFILE';
export const DAILY_ORDERS_PATTERN='DAILY_ORDERS_PATTERN';
export const DAILY_ORDERS_FORECAST='DAILY_ORDERS_FORECAST';
export const OFFLINE_DATA='OFFLINE_DATA';
export const ONLINE_DATA='ONLINE_DATA';
export const RECURRENCY_DATA='RECURRENCY_DATA';
export const RFM_DATA='RFM_DATA';